services:

  reverse-proxy-mock-service:
    image: caddy:latest
    container_name: reverse-proxy-mock-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - shared-network

  mock-service:
    build:
      dockerfile: Dockerfile
    container_name: mock-service
    env_file: ./.env
    ports:
      - ${MOCK_SERVICE_PORT}:${MOCK_SERVICE_PORT}
    networks:
      - shared-network

volumes:
  postgres_data:
    name: stravamap_dev_postgres_auth_data
  caddy_data:
  caddy_config:

networks:
  shared-network: