services:
  node-dev:
    build:
      context: ..
      dockerfile: docker-env/Dockerfile
    volumes:
      - ../:/home/developer/WKS
      - ../docker-env/docker-dev-config/.zshrc:/home/developer/.zshrc
      - ../docker-env/docker-dev-config/.p10k.zsh:/home/developer/.p10k.zsh
    working_dir: /home/developer/WKS
    ports:
      - ${AUTHENTICATION_SERVICE_PORT}:${AUTHENTICATION_SERVICE_PORT}
    tty: true
    stdin_open: true
    command: zsh