services:
  postgres-auth-dev:
    image: postgres:latest
    container_name: postgres-auth-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - shared-network

  dev:
    build:
      dockerfile: Dockerfile
    container_name: node-dev
    stdin_open: true
    tty: true
    restart: "no"
    depends_on:
      - postgres-auth-dev
    working_dir: /home/developer/WKS
    ports:
      - ${AUTHENTICATION_SERVICE_PORT}:${AUTHENTICATION_SERVICE_PORT}
    volumes:
      - ../:/home/developer/WKS
      - ./docker-dev-config/.zshrc:/home/developer/.zshrc
      - ./docker-dev-config/.p10k.zsh:/home/developer/.p10k.zsh
    networks:
      - shared-network

volumes:
  postgres_data:
    name: stravamap_dev_postgres_auth_data

networks:
  shared-network: