name: Deployment

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: |
          cd backend/mock-service
          npm install

      - name: Run lint
        run: |
          cd backend/mock-service
          npm run lint

  pull_on_serv:
    runs-on: ubuntu-latest
    needs: lint
    steps:

      - name: Pull git repository into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            cd /home/containers/StravaMap
            git checkout main
            git pull

  refresh_containers:
    runs-on: ubuntu-latest
    needs: pull_on_serv

    steps:

      - name: Build and deploy mock service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            cd /home/containers/StravaMap/backend/mock-service
            docker compose up -d